# Generated by Django 5.0.7 on 2024-08-03 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('url', models.URLField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=25, unique=True)),
                ('n_clicks', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
