# Generated by Django 5.0.7 on 2024-08-03 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=20, unique=True)),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_ag', models.DateTimeField(auto_now_add=True)),
                ('loan_status', models.CharField(choices=[('granted', 'Granted'), ('reject_pay', 'Reject Payment'), ('reject_hist', 'Reject History'), ('reject_age', 'Reject Age')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.user')),
            ],
        ),
    ]
