# Generated by Django 5.0.7 on 2024-08-03 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='created_ag',
            new_name='created_at',
        ),
    ]
