# Generated by Django 5.0.7 on 2024-08-03 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_rename_created_ag_loan_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_status',
            field=models.CharField(choices=[('granted', 'Granted'), ('reject_pay', 'Reject Payment'), ('reject_hist', 'Reject History'), ('reject_age', 'Reject Age'), ('settled', 'Settled')], max_length=20),
        ),
    ]
